# Generated by Django 2.1.5 on 2019-03-28 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('origin_primary', models.CharField(blank=True, max_length=25, null=True)),
                ('origin_secondary', models.CharField(blank=True, max_length=25, null=True)),
                ('ability_primary', models.CharField(blank=True, max_length=5, null=True)),
                ('ability_secondary', models.CharField(blank=True, max_length=5, null=True)),
                ('skill_primary', models.CharField(blank=True, max_length=100, null=True)),
                ('skill_secondary', models.CharField(blank=True, max_length=100, null=True)),
                ('random_skill', models.CharField(blank=True, max_length=100, null=True)),
                ('bonus_primary', models.CharField(blank=True, max_length=100, null=True)),
                ('bonus_secondary', models.CharField(blank=True, max_length=100, null=True)),
                ('ac', models.IntegerField(blank=True, null=True)),
                ('fort', models.IntegerField(blank=True, null=True)),
                ('ref', models.IntegerField(blank=True, null=True)),
                ('will', models.IntegerField(blank=True, null=True)),
                ('defense_primary', models.TextField(blank=True, max_length=1000, null=True)),
                ('defense_secondary', models.TextField(blank=True, max_length=1000, null=True)),
                ('lvl_1_primary', models.TextField(blank=True, max_length=1000, null=True)),
                ('lvl_1_secondary', models.TextField(blank=True, max_length=1000, null=True)),
                ('lvl_2_or_6_primary', models.TextField(blank=True, max_length=1000, null=True)),
                ('lvl_2_or_6_secondary', models.TextField(blank=True, max_length=1000, null=True)),
                ('novice_primary', models.TextField(blank=True, max_length=1000, null=True)),
                ('novice_secondary', models.TextField(blank=True, max_length=1000, null=True)),
                ('utility_primary', models.TextField(blank=True, max_length=1000, null=True)),
                ('utility_secondary', models.TextField(blank=True, max_length=1000, null=True)),
                ('expert_primary', models.TextField(blank=True, max_length=1000, null=True)),
                ('expert_secondary', models.TextField(blank=True, max_length=1000, null=True)),
                ('playerId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=25)),
                ('ability', models.CharField(max_length=5)),
                ('skill', models.CharField(max_length=100)),
                ('bonus', models.CharField(max_length=100)),
                ('ac', models.IntegerField()),
                ('fort', models.IntegerField()),
                ('ref', models.IntegerField()),
                ('will', models.IntegerField()),
                ('defense', models.TextField(max_length=1000)),
                ('lvl_1', models.TextField(max_length=1000)),
                ('lvl_2_or_6', models.TextField(max_length=1000)),
                ('novice', models.TextField(max_length=1000)),
                ('utility', models.TextField(max_length=1000)),
                ('expert', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='OriginSecondary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=25)),
                ('ability', models.CharField(max_length=5)),
                ('skill', models.CharField(max_length=100)),
                ('bonus', models.CharField(max_length=100)),
                ('ac', models.IntegerField()),
                ('fort', models.IntegerField()),
                ('ref', models.IntegerField()),
                ('will', models.IntegerField()),
                ('defense', models.TextField(max_length=1000)),
                ('lvl_1', models.TextField(max_length=1000)),
                ('lvl_2_or_6', models.TextField(max_length=1000)),
                ('novice', models.TextField(max_length=1000)),
                ('utility', models.TextField(max_length=1000)),
                ('expert', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=25)),
                ('key_ability', models.CharField(max_length=25)),
            ],
        ),
    ]
