# Generated by Django 2.1.5 on 2019-03-28 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='playerId',
            new_name='user',
        ),
    ]
