# Generated by Django 2.1.5 on 2019-02-13 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='origin',
            old_name='lvl',
            new_name='defense',
        ),
    ]
