# Generated by Django 2.1.5 on 2019-07-09 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190328_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GammaCharacterSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('archived', models.BooleanField(default=False, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('lvl', models.IntegerField(default=1, null=True)),
                ('origin1_first', models.CharField(blank=True, max_length=255, null=True)),
                ('origin2_second', models.CharField(blank=True, max_length=255, null=True)),
                ('strength', models.IntegerField(default=0, null=True)),
                ('dexterity', models.IntegerField(default=0, null=True)),
                ('wisdom', models.IntegerField(default=0, null=True)),
                ('constitution', models.IntegerField(default=0, null=True)),
                ('intelligence', models.IntegerField(default=0, null=True)),
                ('charisma', models.IntegerField(default=0, null=True)),
                ('skill1', models.CharField(blank=True, max_length=255, null=True)),
                ('skill2', models.CharField(blank=True, max_length=255, null=True)),
                ('skill3', models.CharField(blank=True, max_length=255, null=True)),
                ('skill1_mod', models.IntegerField(default=0, null=True)),
                ('skill2_mod', models.IntegerField(default=0, null=True)),
                ('skill3_mod', models.IntegerField(default=0, null=True)),
                ('hp', models.IntegerField(default=0, null=True)),
                ('speed', models.IntegerField(default=6, null=True)),
                ('ac', models.IntegerField(default=0, null=True)),
                ('fort', models.IntegerField(default=0, null=True)),
                ('ref', models.IntegerField(default=0, null=True)),
                ('will', models.IntegerField(default=0, null=True)),
                ('overcharge_bonus1', models.CharField(blank=True, max_length=255, null=True)),
                ('overcharge_bonus2', models.CharField(blank=True, max_length=255, null=True)),
                ('defense1', models.CharField(blank=True, max_length=255, null=True)),
                ('defense2', models.CharField(blank=True, max_length=255, null=True)),
                ('defense_ability1', models.CharField(blank=True, max_length=9255, null=True)),
                ('defense_ability2', models.CharField(blank=True, max_length=9255, null=True)),
                ('critical_choice_lvl_2', models.CharField(blank=True, max_length=2955, null=True)),
                ('critical_choice_lvl_6', models.CharField(blank=True, max_length=2955, null=True)),
                ('critical1', models.CharField(blank=True, max_length=2955, null=True)),
                ('critical2', models.CharField(blank=True, max_length=2955, null=True)),
                ('novice_1', models.CharField(blank=True, max_length=9255, null=True)),
                ('novice_2', models.CharField(blank=True, max_length=9255, null=True)),
                ('utility_choice_lvl_3', models.CharField(blank=True, max_length=9255, null=True)),
                ('utility_choice_lvl_7', models.CharField(blank=True, max_length=9255, null=True)),
                ('utility_1', models.CharField(blank=True, max_length=9255, null=True)),
                ('utility_2', models.CharField(blank=True, max_length=9255, null=True)),
                ('expert_choice_lvl_5', models.CharField(blank=True, max_length=9255, null=True)),
                ('expert_choice_lvl_9', models.CharField(blank=True, max_length=9255, null=True)),
                ('expert_1', models.CharField(blank=True, max_length=9255, null=True)),
                ('expert_2', models.CharField(blank=True, max_length=9255, null=True)),
                ('campaign', models.ManyToManyField(to='core.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('ac_bonus', models.IntegerField(default=0, null=True)),
                ('equipped', models.BooleanField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('cost', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('dice', models.CharField(blank=True, max_length=255, null=True)),
                ('bonus', models.IntegerField(default=0, null=True)),
                ('accuracy', models.IntegerField(default=0, null=True)),
                ('ability_modifier', models.CharField(blank=True, max_length=255, null=True)),
                ('equipped', models.BooleanField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='origin',
            name='ac',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='origin',
            name='fort',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='origin',
            name='ref',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='origin',
            name='will',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='originsecondary',
            name='ac',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='originsecondary',
            name='fort',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='originsecondary',
            name='ref',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='originsecondary',
            name='will',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='gammacharactersheet',
            name='gear',
            field=models.ManyToManyField(to='core.Gear'),
        ),
        migrations.AddField(
            model_name='gammacharactersheet',
            name='inventory_items',
            field=models.ManyToManyField(to='core.InventoryItem'),
        ),
        migrations.AddField(
            model_name='gammacharactersheet',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gammacharactersheet',
            name='weapons',
            field=models.ManyToManyField(to='core.Weapon'),
        ),
    ]
