# Generated by Django 2.1.5 on 2019-02-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190213_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='origin',
            name='bonus',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='origin',
            name='skill',
            field=models.CharField(max_length=100),
        ),
    ]
