# Generated by Django 2.1.5 on 2019-07-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190709_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='gammacharactersheet',
            name='temp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
