# Generated by Django 2.1.5 on 2019-07-30 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_gammacharactersheet_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gammacharactersheet',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='gammacharactersheet',
            name='gear',
        ),
        migrations.RemoveField(
            model_name='gammacharactersheet',
            name='inventory_items',
        ),
        migrations.RemoveField(
            model_name='gammacharactersheet',
            name='weapons',
        ),
        migrations.AddField(
            model_name='gear',
            name='gammaCharacterSheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gear', to='core.GammaCharacterSheet'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='gammaCharacterSheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_item', to='core.GammaCharacterSheet'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='gammaCharacterSheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weapon', to='core.GammaCharacterSheet'),
        ),
    ]
