# Generated by Django 2.1.5 on 2019-07-30 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190730_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='gammacharactersheet',
            name='campaign',
            field=models.ManyToManyField(to='core.Campaign'),
        ),
    ]
