# Generated by Django 2.1.5 on 2019-02-17 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='o_primary',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='o_secondary',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
