# Generated by Django 2.1.5 on 2019-03-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190301_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='random_skill',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
